### ISSUE TITLE
how to download if you have a library login ?

### ISSUE THREAD

**Issue by a-eid** [papapon/lynda-dl#2]

**Comment by papapon** [comment]
I didn't know it was possible. 
Have you tried to replace login and password by your library card number and library card pin?

**Comment by a-eid** [comment]
It would not work because every organization login URL is different.

**Comment by papapon** [comment]
What your login url looks like?

**Comment by a-eid** [comment]
https://www.lynda.com/portal/sip?org=dclibrary.org

**Comment by papapon** [comment]
My script is based on youtube-dl tool. Your issue is explained [here](https://github.com/rg3/youtube-dl/issues/5926)
Good luck.

**Comment by a-eid** [comment]
I'll take a look at that, thank you.
